# Generated by Django 3.0.7 on 2020-06-11 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('addition_bytes', models.IntegerField(default=100)),
                ('subtraction_bytes', models.IntegerField(default=100)),
                ('algebra_bytes', models.IntegerField(default=100)),
                ('multiplication_bytes', models.IntegerField(default=100)),
                ('division_bytes', models.IntegerField(default=100)),
                ('addition_questions', models.IntegerField(default=0)),
                ('subtraction_questions', models.IntegerField(default=0)),
                ('algebra_questions', models.IntegerField(default=0)),
                ('multiplication_questions', models.IntegerField(default=0)),
                ('division_questions', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
